### ISSUE TITLE
Questions about predict

### ISSUE THREAD

**Issue by dishegg** [YaoZhang93/MAML#3]
I use my own dataset for training, and I get RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 4 when predicting，I can predict if i only use nnunet frame

**Comment by YaoZhang93** [comment]
Hi,

Would you put up the command you run and the whole error text?

Best,
Yao

**Comment by dishegg** [comment]
> 你好
> 
> 你会把你运行的命令和整个错误文本放上去吗？
> 
> 贝斯特， 姚

Traceback (most recent call last):
  File "nnunet/inference/predict_simple.py", line 225, in <module>
    main()
  File "nnunet/inference/predict_simple.py", line 221, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "/content/drive/MyDrive/nnUNetframe/nnUNet/nnunet/inference/predict.py", line 664, in predict_from_folder
    disable_postprocessing=disable_postprocessing)
  File "/content/drive/MyDrive/nnUNetframe/nnUNet/nnunet/inference/predict.py", line 219, in predict_cases
    mixed_precision=mixed_precision)[1]
  File "/content/drive/MyDrive/nnUNetframe/nnUNet/nnunet/training/network_training/MAMLTrainerV2.py", line 226, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/content/drive/MyDrive/nnUNetframe/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 522, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/content/drive/MyDrive/nnUNetframe/nnUNet/nnunet/network_architecture/neural_network.py", line 148, in predict_3D
    verbose=verbose)
  File "/content/drive/MyDrive/nnUNetframe/nnUNet/nnunet/network_architecture/neural_network.py", line 386, in _internal_predict_3D_3Dconv_tiled
    gaussian_importance_map)[0]
  File "/content/drive/MyDrive/nnUNetframe/nnUNet/nnunet/network_architecture/neural_network.py", line 533, in _internal_maybe_mirror_and_pred_3D
    result_torch += 1 / num_results * pred
RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 4
before crop: (2, 267, 128, 128) after crop: (2, 21, 110, 119) spacing: [1. 1. 1.]

**Comment by dishegg** [comment]
I will provide the public data set I use. It is not very large, about 50M. It does not need to be converted. Just run plan_and_preprocess directly. Can you please leave your mailbox?

**Comment by YaoZhang93** [comment]
Hi Tong,

Thanks for reporting this issue. I set the output from an improper layer of the network, which leads to this issue. It has been fixed now and you can have a try with the updated version.

Best regards,
Yao

**Comment by dishegg** [comment]
ok, this works fine thank you very much for your work hope your next article will also have good results
